### ISSUE TITLE
Metabase in docker: Can't find files

### ISSUE THREAD

**Issue by GregTheGreek** [Markenson/csv-metabase-driver#20]
I'm having a difficult time running this in docker and having the files found, are you aware of a way to do this?

I've tried absolute paths to:
- mounted file through docker volumes
- local filesystem

**Comment by Markenson** [comment]
Hi!

It works outside docker?

After mount docker volume your files appears inside container?

**Comment by citron** [comment]
same problem. Solved it by putting the jar ( in a bottle ? no... )  in /tmp instead of /plugins.
/tmp seems to be the place where plugins are expected in the docker version

**Comment by Markenson** [comment]
OK, @citron then I'll close this issue.

**Comment by k4j8** [comment]
I was able to use the CSV plugin with Metabase in Docker by saving `csv.metabase-driver.jar` in the same directory as `docker-compose.yml` and then adding the following volume bind mount to `docker-compose.yml`:
```yaml
services:
  metabase:
    volumes:
      - ./csv.metabase-driver.jar:/plugins/csv.metabase-driver.jar
```
